# xtquant-proxy 配置文件
# 使用环境变量 APP_MODE 切换模式: mock, dev, prod
# 例如: set APP_MODE=dev (Windows) 或 export APP_MODE=dev (Linux/Mac)

app:
  name: "xtquant-proxy"
  version: "1.0.0"

# 日志配置
logging:
  file: "logs/app.log"  # 主日志文件
  error_file: "logs/error.log"  # 错误日志文件（仅ERROR及以上级别）
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"
  rotation: "10 MB"  # 日志文件轮转大小（可选：10 MB, 500 KB, 1 day, 12:00 等）
  retention: "30 days"  # 日志保留时间（可选：30 days, 1 week, 2 months 等）
  compression: "zip"  # 压缩格式（可选：zip, gz, tar.gz, bz2）
  console_output: true  # 是否同时输出到控制台（开发时建议true，生产可设为false）
  backtrace: true  # 是否显示完整堆栈跟踪
  diagnose: false  # 是否显示诊断信息（仅在调试复杂问题时启用）

# gRPC 配置
grpc:
  enabled: true
  host: "0.0.0.0"
  port: 50051
  max_workers: 10
  max_message_length: 52428800  # 50MB

# xtquant配置
xtquant:
  # QMT安装路径
  qmt_userdata_path: "C:/quant/国金QMT交易端模拟/userdata_mini"
  
  # 数据路径配置
  data:
    path: "./data"
    config_path: "./xtquant/config"

# 模式配置 (通过环境变量 APP_MODE 选择: mock, dev, prod)
modes:
  # mock模式: 不连接xtquant，使用模拟数据，不允许交易
  mock:
    debug: true
    host: "0.0.0.0"
    port: 8000
    log_level: "DEBUG"
    xtquant_mode: "mock"
    allow_real_trading: false
    connect_xtquant: false
    api_keys:
      - "mock-api-key-001"
      - "mock-api-key-002"
    database:
      url: "sqlite:///./app_mock.db"
    redis:
      url: "redis://localhost:6379/0"
    cors:
      allow_origins: ["*"]
  
  # dev模式: 连接xtquant，获取真实数据，不允许交易
  dev:
    debug: true
    host: "0.0.0.0"
    port: 8000
    log_level: "DEBUG"
    xtquant_mode: "dev"
    allow_real_trading: false
    connect_xtquant: true
    api_keys:
      - "dev-api-key-001"
      - "dev-api-key-002"
    database:
      url: "sqlite:///./app_dev.db"
    redis:
      url: "redis://localhost:6379/1"
    cors:
      allow_origins: ["*"]
  
  # prod模式: 连接xtquant，获取真实数据，允许真实交易
  prod:
    debug: false
    host: "0.0.0.0"
    port: 8000
    log_level: "INFO"
    xtquant_mode: "prod"
    allow_real_trading: true
    connect_xtquant: true
    api_keys:
      - "prod-api-key-001"
      - "prod-api-key-002"
    database:
      url: "postgresql://user:password@localhost:5432/xtquant_proxy"
    redis:
      url: "redis://localhost:6379/0"
    cors:
      allow_origins: ["https://yourdomain.com"]
    # 生产环境可以关闭控制台输出，只输出到文件
    logging:
      console_output: false
      diagnose: false

# 安全配置
security:
  secret_key: "change-this-to-secure-key-in-production"
  api_key_header: "X-API-Key"
