# 生产环境配置
app:
  name: "xtquant-proxy"
  version: "1.0.0"
  debug: false
  host: "0.0.0.0"
  port: 8000

# 日志配置
logging:
  level: "INFO"
  file: "logs/app.log"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"

# xtquant配置
xtquant:
  # 接口模式: mock, real, dev
  mode: "real"
  
  # 数据配置
  data:
    path: "./data"
    config_path: "./xtquant/config"
  
  # 交易配置
  trading:
    # 生产环境允许真实下单
    allow_real_trading: true
    # 真实交易账户配置
    real_accounts:
      - account_id: "real_account_001"
        password: "real_password_001"
        client_id: 1
      - account_id: "real_account_002"
        password: "real_password_002"
        client_id: 2

# 安全配置
security:
  secret_key: "prod-secret-key-change-this-to-secure-key"
  api_key_header: "X-API-Key"
  # API密钥列表（生产环境）
  api_keys:
    - "prod-api-key-001"
    - "prod-api-key-002"

# 数据库配置
database:
  url: "postgresql://user:password@localhost:5432/xtquant_proxy"

# Redis配置
redis:
  url: "redis://localhost:6379/0"

# CORS配置
cors:
  allow_origins: ["https://yourdomain.com"]
  allow_credentials: true
  allow_methods: ["GET", "POST", "PUT", "DELETE"]
  allow_headers: ["*"]
