# 测试环境配置
app:
  name: "xtquant-proxy"
  version: "1.0.0"
  debug: true
  host: "0.0.0.0"
  port: 8000

# 日志配置
logging:
  level: "DEBUG"
  file: "logs/app_test.log"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"

# xtquant配置
xtquant:
  # 接口模式: mock, real, dev
  mode: "dev"
  
  # 数据配置
  data:
    path: "./data"
    config_path: "./xtquant/config"
  
  # 交易配置
  trading:
    # 测试环境不允许真实下单
    allow_real_trading: false
    # 测试账户配置
    test_account_id: "test_account_001"
    test_password: "test_password"

# 安全配置
security:
  secret_key: "test-secret-key"
  api_key_header: "X-API-Key"
  # API密钥列表（测试环境）
  api_keys:
    - "test-api-key-001"

# 数据库配置
database:
  url: "sqlite:///./app_test.db"

# Redis配置
redis:
  url: "redis://localhost:6379/1"

# CORS配置
cors:
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]
