# 开发环境配置
app:
  name: "xtquant-proxy"
  version: "1.0.0"
  debug: true
  host: "0.0.0.0"
  port: 8000

# 日志配置
logging:
  level: "DEBUG"
  file: "logs/app.log"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"

# xtquant配置
xtquant:
  # 接口模式: mock, real, dev
  # mock: 使用模拟数据
  # real: 使用真实xtquant接口
  # dev: 开发模式，使用真实接口但不下单
  mode: "dev"
  
  # 数据配置
  data:
    path: "./data"
    config_path: "./xtquant/config"
    qmt_userdata_path: "C:/quant/国金QMT交易端模拟/userdata_mini"
  
  # 交易配置
  trading:
    # 开发模式下是否允许真实下单
    allow_real_trading: false
    # 模拟交易账户
    mock_account_id: "mock_account_001"
    # 模拟交易密码
    mock_password: "mock_password"

# 安全配置
security:
  secret_key: "dev-secret-key-change-in-production"
  api_key_header: "X-API-Key"
  # API密钥列表（开发环境）
  api_keys:
    - "dev-api-key-001"
    - "dev-api-key-002"

# 数据库配置（可选）
database:
  url: "sqlite:///./app_dev.db"

# Redis配置（可选）
redis:
  url: "redis://localhost:6379/0"

# CORS配置
cors:
  allow_origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]
